#services:
#  db:
#    image: postgres:latest
#    container_name: postgres-db
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: secret
#      POSTGRES_DB: mydatabase
#    ports:
#      - "5432:5432"
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"